                        </td>
                    </tr>
                    @include('emails.layouts._footer-inner')
                </table>
            </td>
        </tr>
    </table>
</div>
</body>
</html>
