name: USERBBSBACKEND

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: amrgamal194/user-bbs-backend  # Adjust if repo name differs
          ssh-key: ${{ secrets.SERVER_SSH_KEY }}  # SSH key for cloning repo


      - name: Set up SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts
      - name: Deploy to Server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          ssh $SERVER_USER@$SERVER_HOST << 'EOF'
          set -e  # stop if any command fails
          cd /home/api/public_html || exit
          echo "🔄 Pulling latest code..."
          git fetch origin production
          git reset --hard origin/production
          
         
          
          echo "✅ Deployment completed successfully!"
          EOF
